### ISSUE TITLE
Rime table somewhat misleading in construction

### ISSUE THREAD

**Issue by este-rs** [toaq/toaq.github.io#17]
For reference, here is the current shape of the table:

| | | | | | | | | | | | | | |
|-|-|-|-|-|-|-|-|-|-|-|-|-|-|
| a | aq |  |  | aı | ao |  |  |  |  |  |  |  | (ay) |
| u | uq | ua | uaq | uı | uo | uoı | uoq | ue | ueq | uaı | uao |  | uy |
| ı | ıq | ıa | ıaq |  | ıo |  | ıoq | ıe | ıeq | ıaı | ıao | ıu | ıy |
| o | oq | oa | oaq | oı |  |  |  | oe | oeq | oaı |  | ou | oy |
| e | eq | ea | eaq | eı | eo |  |  |  | eoq | eaı |  |  | ey |
| y |  |  |  |  |  |  |  |  |  |  |  |  |  |

Here are my issues with it – albeit I should note that these issues aren’t “breaking” issues and as such this issue is merely a suggestion for improvement:

1. Some values occupying a given column can be miscontrued as “similar”, when in fact they’re not. For example, **ıu** is a monophthong–hiatus–monophthong sequence – /i.u/ – while the value right below it – /ow/ – is a diphthong. One only realizes it when one compares it with the prose above, which rules out the existence of an \*/iw/ diphthong – still, this isn’t as apparent as one could wish, especially since this table is the Single Source of Truth on what rimes there are in the language and what aren’t!
2. The table doesn’t help to internalize what combinations actually make sense, whereas in reality the construction rule for syllables I have in mind – C(V)V(c) – sweeps 90% of the rules that actually govern the rime. In other words, the table could be more “suggestive”.

In kind, I’d like to suggest the folowing layout for the table:

|     |     |     |     |     |     |     |     |     |     |     |     |     |     |     |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| a   | aq  |(ay) | aı  | ao  |     |     |     |     |     |     |     |     |     |     |
| u   | uq  | uy  |     |     | ua  | uaq | uo  | uoq | ue  | ueq | uaı | uao | uoı | uı  |
| ı   | ıq  | ıy  |     |     | ıa  | ıaq | ıo  | ıoq | ıe  | ıeq | ıaı | ıao |     | ıu  |
| o   | oq  | oy  | oı  | ou  | oa  | oaq |     |     | oe  | oeq | oaı |     |     |     |
| e   | eq  | ey  | eı  |     | ea  | eaq | eo  | eoq |     |     | eaı |     |     |     |
| y   |     |     |     |     |     |     |     |     |     |     |     |     |     |     |

This layout helps “segment” the huge rime space into four very memorable chunks:
* simplex vowels //a u ı o e y//, all of which but //y// may be followed by //-q// or by //-y//; (6 + 5 + 5 = 16 rimes)
* the 5 diphthongs: //aı ao oı ou eı//; (5 rimes)
* the bulk of the rime table: any of //u ı o e// + any of //a(q) o(q) e(q) aı//; (4 × 7 − four “repeats” \*//oo(q) ee(q)// = 24 rimes)
* the odds-and-ends //uao ıao uoı uı ıu//. (5 rimes)
* (total = 16 + 5 + 24 + 5 = 50 rimes, counting the probably official, probably not //ay//)

Once again, this sort of change isn’t *necessary*, but in addition to beginner-approachability, it would help bringing the unending speculation surrounding which rimes exist and which don’t to a close. (I, for one, return to this table every so often just to see if I’ve missed anything, and I often find that I am missing *something*.) Looking forward to yourall comments.

**Comment by solpahi** [comment]
This looks reasonable. 

Two comments:
1. The **-Vy** rime column should remain to the right of all the **-aq**/**-aV** rimes. Compare the order of the diphthongs in the letter names (s-AQ-seoq, r-AI-rua, l-AO-lıq). The **-Vy** rimes are "ranked lower". I would leave the **-Vy** column at the very right of the table, because then ⟨y⟩ is not mixed in with all the other rimes, but anywhere to the right of **-aq**/**-aV** is technically possible.
2. The **-ao** **-ou** column: pedantically, at least based on my own pronunciation, **-ao** and **-ou** are not identical: I pronounce **-ao** with a long [a:] when the word is monosyllabic, e.g. in **jaq sao** -> [sa:.o]/[sa:.ʊ], but as a falling diphthong if it's a longer word, e.g. **maoja** -> [maʊ]. (This could be added as a footnote in that section of the refgram, or it could be ignored as idiosyncrasy. Whether it's worth splitting the columns for this I will leave for others to decide. As this distinction was already not reflected in the original table, this isn't a critique of your proposed re-arrangement, and more something that I felt I should probably mention in case it would be deemed relevant.)
